services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: DuckDNS
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - config:/config
    restart: unless-stopped

networks:
  default:
    extrenal: true
    name: nextcloud

volumes:
  config:
