services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: Nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - app_config:/config
      - app_data:/data
      - /media/storage:/Storage
      - /media/NFS-WD:/media/NFS-WD
    ports:
      - 443:443
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: Nextcloud-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - db_config:/config
    - db_data:/data
    ports:
      - 3306:3306
    restart: unless-stopped
  code:
    image: collabora/code:latest
    container_name: Nextcloud-office
    restart: unless-stopped
    environment:
      - password=${COLLABORA_PASSWORD}
      - username=${COLLABORA_USERNAME}
      - domain=${COLLABORA_DOMAIN}
      - extra_params=--o:ssl.enable=true
    ports:
      - 9980:9980
  cloudflared_nextcloud:
    container_name: Nextcloud-Domain
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${NEXTCLOUD_TOKEN}
    restart: unless-stopped
  cloudflared_collabora:
    container_name: Office-Domain
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${COLLABORA_TOKEN}
    restart: unless-stopped
networks:
  default:
    external: true
    name: Apps-Network
volumes:
  app_config:
  app_data:
  db_config:
  db_data:
