services:
  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=21600
      - TZ=Europe/Athens
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external: true
    name: Apps-Network
