services:
  ytdl_material:
    container_name: YoutTube-dl
    environment:
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
    restart: unless-stopped
    volumes:
      - config:/app/appdata
      - audio:/app/audio
      - /media/youtube-dl:/app/video
      - subscriptions:/app/subscriptions
      - users:/app/users
    ports:
      - 8998:17442
    image: tzahi12345/youtubedl-material:latest
networks:
  default:
    external: true
    name: Apps-Network
volumes:
  config:
  audio:
  subscriptions:
  users:
