services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: Uptime-Kuma
    volumes:
      - data:/app/data
    ports:
      - "3001:3001"
    restart: always
networks:
  default:
    external: true
    name: Apps-Network
volumes:
  data:
