services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: Syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - config:/config
      - appdata:/Appdta
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
networks:
  default:
    external: true
    name: Apps-Network
volumes:
  config:
  appdata:
